import type { PlantCard } from "@/lib/game/types";

export const PLANT_CARDS: PlantCard[] = [
  {
    id: "strawberry-bush",
    name: "Strawberry Bush",
    points: 3,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "clover-patch",
    name: "Clover Patch",
    points: 1,
    waterCapacity: 1,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    points: 4,
    waterCapacity: 3,
    decayPerRound: 0,
    requiresUpkeep: false,
  },
  {
    id: "barrel-cactus",
    name: "Barrel Cactus",
    points: 7,
    waterCapacity: 4,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "lavender",
    name: "Lavender",
    points: 4,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "tomato-vine",
    name: "Tomato Vine",
    points: 5,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "basil",
    name: "Basil",
    points: 3,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "orchid",
    name: "Orchid",
    points: 10,
    waterCapacity: 3,
    decayPerRound: 2,
    requiresUpkeep: true,
  },
  {
    id: "bird-of-paradise",
    name: "Bird-of-Paradise",
    points: 9,
    waterCapacity: 4,
    decayPerRound: 2,
    requiresUpkeep: true,
  },
  {
    id: "venus-flytrap",
    name: "Venus Flytrap",
    points: 6,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "pitcher-plant",
    name: "Pitcher Plant",
    points: 4,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "sundew-cluster",
    name: "Sundew Cluster",
    points: 3,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "cobra-lily",
    name: "Cobra Lily",
    points: 8,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "bladderwort",
    name: "Bladderwort",
    points: 5,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "thornmaw-bramble",
    name: "Thornmaw Bramble",
    points: 6,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "sporefang-vine",
    name: "Sporefang Vine",
    points: 6,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "gloomtrap-shrub",
    name: "Gloomtrap Shrub",
    points: 9,
    waterCapacity: 4,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "mawroot-bulb",
    name: "Mawroot Bulb",
    points: 5,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "carrion-bloom",
    name: "Carrion Bloom",
    points: 8,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "razorleaf-net",
    name: "Razorleaf Net",
    points: 6,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "apex-devourer",
    name: "Apex Devourer",
    points: 12,
    waterCapacity: 4,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "mint",
    name: "Mint",
    points: 2,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "sunpetal-daisy",
    name: "Sunpetal Daisy",
    points: 3,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "golden-marigold",
    name: "Golden Marigold",
    points: 6,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "night-lantern-flower",
    name: "Night Lantern Flower",
    points: 5,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "bloomkeeper-ivy",
    name: "Bloomkeeper Ivy",
    points: 4,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "crowned-peony",
    name: "Crowned Peony",
    points: 9,
    waterCapacity: 4,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "petal-archivist",
    name: "Petal Archivist",
    points: 3,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "nectar-fountain",
    name: "Nectar Fountain",
    points: 7,
    waterCapacity: 4,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "sun-choir-shrub",
    name: "Sun Choir Shrub",
    points: 6,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "dewglass-orchid",
    name: "Dewglass Orchid",
    points: 10,
    waterCapacity: 3,
    decayPerRound: 2,
    requiresUpkeep: true,
  },
  {
    id: "petal-alchemist",
    name: "Petal Alchemist",
    points: 4,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "sunroot-conductor",
    name: "Sunroot Conductor",
    points: 8,
    waterCapacity: 4,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "verdant-festival-tree",
    name: "Verdant Festival Tree",
    points: 12,
    waterCapacity: 5,
    decayPerRound: 1,
    requiresUpkeep: true,
  },
  {
    id: "sandspire-cactus",
    name: "Sandspire Cactus",
    points: 4,
    waterCapacity: 2,
    decayPerRound: 0,
    requiresUpkeep: false,
  },
  {
    id: "dustbloom-succulent",
    name: "Dustbloom Succulent",
    points: 6,
    waterCapacity: 3,
    decayPerRound: 0,
    requiresUpkeep: false,
  },
  {
    id: "thornbark-shrub",
    name: "Thornbark Shrub",
    points: 5,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "parched-root-network",
    name: "Parched Root Network",
    points: 7,
    waterCapacity: 4,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "sunscorch-agave",
    name: "Sunscorch Agave",
    points: 8,
    waterCapacity: 3,
    decayPerRound: 0,
    requiresUpkeep: false,
  },
  {
    id: "wither-sage",
    name: "Wither Sage",
    points: 4,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "desert-mat-creeper",
    name: "Desert Mat Creeper",
    points: 2,
    waterCapacity: 1,
    decayPerRound: 0,
    requiresUpkeep: false,
  },
  {
    id: "scorchvine",
    name: "Scorchvine",
    points: 6,
    waterCapacity: 3,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "mirage-bloom",
    name: "Mirage Bloom",
    points: 5,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "ironwood-sapling",
    name: "Ironwood Sapling",
    points: 9,
    waterCapacity: 5,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "ashflower-bush",
    name: "Ashflower Bush",
    points: 6,
    waterCapacity: 2,
    decayPerRound: 1,
    requiresUpkeep: false,
  },
  {
    id: "dominion-baobab",
    name: "Dominion Baobab",
    points: 12,
    waterCapacity: 5,
    decayPerRound: 1,
    requiresUpkeep: false,
  }
];

export const PLANT_CARD_IDS = PLANT_CARDS.map((card) => card.id);
